services:
  # Level 1: Basic Services (db, redis, app)
  # Level 3: Add dedicated networks and volumes
  # Level 4: Add healthchecks and resource limits
  # Level 5: Add secrets and .env validation

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    restart: always
    # TODO: Environment (Level 1)
    environment:     
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    # TODO: Volumes (Level 3)
    # volumes:
    #   - postgres_data:/var/lib/postgresql
    # TODO: Healthcheck (Level 4)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d password"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    # TODO: Build & Ports (Level 1)
    build: ./notes-app
    ports:
      - "8081:8081"
      
    # TODO: Multi-stage build (Level 2)
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
    depends_on:
      db:
        condition: service_healthy
    # TODO: Networks (Level 3)
    # TODO: Depends_on & Limits (Level 4)
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    # TODO: Secrets (Level 5)

# secrets:
#   db_password:
#     file: ./db_password.txt

# volumes:
#   postgres_data:
#     driver: 
