apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: networking-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
